   /src
     /components
       /Modal
         Modal.js
         Modal.css
       /Card
         Card.js
         Card.css
     /pages
       /Login
         Login.js
         Login.css
       /Dashboard
         Dashboard.js
         Dashboard.css
     /api
       api.js
     App.js
     index.js