# Generated by Django 6.0.1 on 2026-03-09 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='EstadoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Estados de Caso',
                'db_table': 'EstadoCaso',
            },
        ),
        migrations.CreateModel(
            name='EstadoOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Pendiente, Procesando, Exitoso, Fallido, Rechazado', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estados de OCR',
                'db_table': 'EstadoOCR',
            },
        ),
        migrations.CreateModel(
            name='EstadoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estados de Reporte',
                'db_table': 'EstadoReporte',
            },
        ),
        migrations.CreateModel(
            name='TipoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Mensaje',
                'db_table': 'TipoMensaje',
            },
        ),
        migrations.CreateModel(
            name='TipoSancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('duracion_dias', models.IntegerField(blank=True, null=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Sanción',
                'db_table': 'TipoSancion',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Usuario',
                'db_table': 'TipoUsuario',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('contrasena', models.CharField(db_column='contrasena', max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('verificado', models.BooleanField(default=False)),
                ('imagen_perfil', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen_ine_frontal_url', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen_ine_trasera_url', models.CharField(blank=True, max_length=500, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='último acceso')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios_set', related_query_name='usuario', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios_set', related_query_name='usuario', to='auth.permission', verbose_name='user permissions')),
                ('id_tipo_usuario', models.ForeignKey(db_column='idTipoUsuario', on_delete=django.db.models.deletion.PROTECT, to='members.tipousuario')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_abierto', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('entidad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_conclusion', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('imagen1', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen2', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen3', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen4', models.CharField(blank=True, max_length=500, null=True)),
                ('vistas', models.IntegerField(default=0)),
                ('compartido', models.IntegerField(default=0)),
                ('prioridad', models.IntegerField(default=0)),
                ('id_beneficiario', models.ForeignKey(db_column='idBeneficiario', on_delete=django.db.models.deletion.PROTECT, related_name='casos_beneficiario', to=settings.AUTH_USER_MODEL)),
                ('id_estado', models.ForeignKey(db_column='idEstado', on_delete=django.db.models.deletion.PROTECT, to='members.estadocaso')),
            ],
            options={
                'verbose_name_plural': 'Casos',
                'db_table': 'Casos',
            },
        ),
        migrations.CreateModel(
            name='Conversaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('esta_activa', models.BooleanField(default=True)),
                ('id_caso', models.ForeignKey(blank=True, db_column='idCaso', null=True, on_delete=django.db.models.deletion.PROTECT, to='members.casos')),
                ('id_usuario1', models.ForeignKey(db_column='idUsuario1', on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones_usuario1', to=settings.AUTH_USER_MODEL)),
                ('id_usuario2', models.ForeignKey(db_column='idUsuario2', on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones_usuario2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conversaciones',
                'db_table': 'Conversaciones',
            },
        ),
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_compromiso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('estado_donacion', models.CharField(default='Pendiente', max_length=50)),
                ('es_anonima', models.BooleanField(default=False)),
                ('mensaje_donador', models.TextField(blank=True, null=True)),
                ('id_caso', models.ForeignKey(db_column='idCaso', on_delete=django.db.models.deletion.PROTECT, to='members.casos')),
                ('id_donador', models.ForeignKey(db_column='idDonador', on_delete=django.db.models.deletion.PROTECT, related_name='donaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Donaciones',
                'db_table': 'Donaciones',
            },
        ),
        migrations.CreateModel(
            name='DocumentosOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(help_text='INE_FRONTAL, INE_TRASERA, COMPROBANTE_DOMICILIO, EVIDENCIA_CASO', max_length=50)),
                ('id_relacionado', models.IntegerField(blank=True, help_text='ID del caso o evidencia relacionada', null=True)),
                ('ruta_imagen', models.CharField(max_length=500)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('intentos_procesamiento', models.IntegerField(default=0)),
                ('nombre_extraido', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido_paterno_extraido', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno_extraido', models.CharField(blank=True, max_length=100, null=True)),
                ('curp_extraida', models.CharField(blank=True, max_length=18, null=True)),
                ('clave_electoral_extraida', models.CharField(blank=True, max_length=18, null=True)),
                ('fecha_nacimiento_extraida', models.DateField(blank=True, null=True)),
                ('sexo_extraido', models.CharField(blank=True, max_length=1, null=True)),
                ('direccion_extraida', models.CharField(blank=True, max_length=300, null=True)),
                ('vigencia_extraida', models.CharField(blank=True, max_length=10, null=True)),
                ('confianza_ocr', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de confianza del OCR (0-100)', max_digits=5, null=True)),
                ('datos_validados', models.BooleanField(default=False)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('notas_validacion', models.TextField(blank=True, null=True)),
                ('respuesta_ocr_completa', models.JSONField(blank=True, help_text='Respuesta completa del servicio OCR', null=True)),
                ('id_usuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, db_column='validadoPor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_ocr', to=settings.AUTH_USER_MODEL)),
                ('id_estado', models.ForeignKey(db_column='idEstado', on_delete=django.db.models.deletion.PROTECT, to='members.estadoocr')),
            ],
            options={
                'verbose_name_plural': 'Documentos OCR',
                'db_table': 'DocumentosOCR',
            },
        ),
        migrations.CreateModel(
            name='Evidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_archivo', models.CharField(blank=True, max_length=20, null=True)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('imagen1', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen2', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_publico', models.BooleanField(default=True)),
                ('id_caso', models.ForeignKey(db_column='idCaso', on_delete=django.db.models.deletion.CASCADE, to='members.casos')),
                ('id_usuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Evidencias',
                'db_table': 'Evidencias',
            },
        ),
        migrations.CreateModel(
            name='LogOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('tiempo_procesamiento_ms', models.IntegerField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_anterior', models.ForeignKey(blank=True, db_column='estadoAnterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_estado_anterior', to='members.estadoocr')),
                ('estado_nuevo', models.ForeignKey(db_column='estadoNuevo', on_delete=django.db.models.deletion.PROTECT, related_name='logs_estado_nuevo', to='members.estadoocr')),
                ('id_documento_ocr', models.ForeignKey(db_column='idDocumentoOCR', on_delete=django.db.models.deletion.PROTECT, to='members.documentosocr')),
            ],
            options={
                'verbose_name_plural': 'Logs OCR',
                'db_table': 'LogOCR',
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('evidencia1', models.CharField(blank=True, max_length=500, null=True)),
                ('evidencia2', models.CharField(blank=True, max_length=500, null=True)),
                ('evidencia3', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('id_caso', models.ForeignKey(blank=True, db_column='idCaso', null=True, on_delete=django.db.models.deletion.PROTECT, to='members.casos')),
                ('id_estado', models.ForeignKey(db_column='idEstado', on_delete=django.db.models.deletion.PROTECT, to='members.estadoreporte')),
                ('id_usuario_reportado', models.ForeignKey(db_column='idUsuarioReportado', on_delete=django.db.models.deletion.PROTECT, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_reporte', models.ForeignKey(db_column='idUsuarioReporte', on_delete=django.db.models.deletion.PROTECT, related_name='reportes_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reportes',
                'db_table': 'Reportes',
            },
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('adjunto', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_leido', models.DateTimeField(blank=True, null=True)),
                ('es_leido', models.BooleanField(default=False)),
                ('es_eliminado', models.BooleanField(default=False)),
                ('id_conversacion', models.ForeignKey(db_column='idConversacion', on_delete=django.db.models.deletion.CASCADE, to='members.conversaciones')),
                ('id_emisor', models.ForeignKey(db_column='idEmisor', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_tipo', models.ForeignKey(db_column='idTipo', on_delete=django.db.models.deletion.PROTECT, to='members.tipomensaje')),
            ],
            options={
                'verbose_name_plural': 'Mensajes',
                'db_table': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Sanciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('es_activa', models.BooleanField(default=True)),
                ('id_reporte', models.ForeignKey(db_column='idReporte', on_delete=django.db.models.deletion.PROTECT, to='members.reportes')),
                ('id_usuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_tipo_sancion', models.ForeignKey(db_column='idTipoSancion', on_delete=django.db.models.deletion.PROTECT, to='members.tiposancion')),
            ],
            options={
                'verbose_name_plural': 'Sanciones',
                'db_table': 'Sanciones',
            },
        ),
        migrations.CreateModel(
            name='CasoCategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_caso', models.ForeignKey(db_column='idCaso', on_delete=django.db.models.deletion.CASCADE, to='members.casos')),
                ('id_categoria', models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.PROTECT, to='members.categorias')),
            ],
            options={
                'verbose_name_plural': 'Caso Categorías',
                'db_table': 'CasoCategorias',
                'indexes': [models.Index(fields=['id_caso'], name='CasoCategor_idCaso_573897_idx'), models.Index(fields=['id_categoria'], name='CasoCategor_idCateg_6bd79d_idx')],
                'unique_together': {('id_caso', 'id_categoria')},
            },
        ),
        migrations.AddIndex(
            model_name='conversaciones',
            index=models.Index(fields=['id_usuario1', 'id_usuario2'], name='Conversacio_idUsuar_23f1ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversaciones',
            unique_together={('id_usuario1', 'id_usuario2', 'id_caso')},
        ),
        migrations.AddIndex(
            model_name='donaciones',
            index=models.Index(fields=['id_caso'], name='Donaciones_idCaso_473a00_idx'),
        ),
        migrations.AddIndex(
            model_name='donaciones',
            index=models.Index(fields=['id_donador'], name='Donaciones_idDonad_fcbad6_idx'),
        ),
        migrations.AddIndex(
            model_name='donaciones',
            index=models.Index(fields=['fecha_compromiso'], name='Donaciones_fecha_c_e4cf5c_idx'),
        ),
        migrations.AddIndex(
            model_name='casos',
            index=models.Index(fields=['id_estado'], name='Casos_idEstad_5c1275_idx'),
        ),
        migrations.AddIndex(
            model_name='casos',
            index=models.Index(fields=['id_beneficiario'], name='Casos_idBenef_01ddce_idx'),
        ),
        migrations.AddIndex(
            model_name='casos',
            index=models.Index(fields=['fecha_creacion'], name='Casos_fecha_c_a6330e_idx'),
        ),
        migrations.AddIndex(
            model_name='casos',
            index=models.Index(fields=['latitud', 'longitud'], name='Casos_latitud_c91e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosocr',
            index=models.Index(fields=['id_usuario'], name='DocumentosO_idUsuar_eb3e84_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosocr',
            index=models.Index(fields=['id_estado'], name='DocumentosO_idEstad_57c83e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosocr',
            index=models.Index(fields=['tipo_documento'], name='DocumentosO_tipo_do_1c7be4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosocr',
            index=models.Index(fields=['fecha_subida'], name='DocumentosO_fecha_s_f0d75f_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencias',
            index=models.Index(fields=['id_caso'], name='Evidencias_idCaso_f26cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='logocr',
            index=models.Index(fields=['id_documento_ocr'], name='LogOCR_idDocum_49557c_idx'),
        ),
        migrations.AddIndex(
            model_name='logocr',
            index=models.Index(fields=['fecha_evento'], name='LogOCR_fecha_e_6c6fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='reportes',
            index=models.Index(fields=['id_usuario_reportado'], name='Reportes_idUsuar_535600_idx'),
        ),
        migrations.AddIndex(
            model_name='reportes',
            index=models.Index(fields=['id_estado'], name='Reportes_idEstad_596d16_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajes',
            index=models.Index(fields=['id_conversacion'], name='Mensajes_idConve_2f8df5_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajes',
            index=models.Index(fields=['id_emisor'], name='Mensajes_idEmiso_530a83_idx'),
        ),
        migrations.AddIndex(
            model_name='sanciones',
            index=models.Index(fields=['id_usuario'], name='Sanciones_idUsuar_a8d981_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['correo'], name='Usuarios_correo_34fef3_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['id_tipo_usuario'], name='Usuarios_idTipoU_c3cf83_idx'),
        ),
    ]
