# Generated by Django 6.0.1 on 2026-02-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casos',
            name='monto_objetivo',
        ),
        migrations.RemoveField(
            model_name='casos',
            name='monto_recaudado',
        ),
    ]
