# Generated by Django 6.0.1 on 2026-02-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_casos_monto_objetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='casos',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='casos',
            index=models.Index(fields=['latitud', 'longitud'], name='Casos_latitud_c91e7f_idx'),
        ),
    ]
