# Generated by Django 4.2.29 on 2026-03-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_logocr_id_documento_ocr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donaciones',
            name='monto',
        ),
    ]
