# Generated by Django 4.2.29 on 2026-03-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_donaciones_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donaciones',
            name='es_anonima',
        ),
        migrations.RemoveField(
            model_name='donaciones',
            name='metodo_pago',
        ),
    ]
