# Generated by Django 4.2.29 on 2026-03-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_donaciones_es_anonima_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donaciones',
            old_name='fecha_pago',
            new_name='fecha_donacion',
        ),
    ]
