# Generated by Django 4.2.29 on 2026-03-18 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_donaciones_fecha_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donaciones',
            name='referencia_pago',
        ),
        migrations.AddField(
            model_name='donaciones',
            name='cantidad_donacion',
            field=models.DecimalField(blank=True, db_column='cantidadDonacion', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donaciones',
            name='descripcion_donacion',
            field=models.TextField(blank=True, db_column='descripcionDonacion', null=True),
        ),
        migrations.AddField(
            model_name='donaciones',
            name='id_categoria',
            field=models.ForeignKey(blank=True, db_column='idCategoria', null=True, on_delete=django.db.models.deletion.PROTECT, to='members.categorias'),
        ),
        migrations.AddField(
            model_name='donaciones',
            name='id_tipo_donacion',
            field=models.IntegerField(blank=True, db_column='idTipoDonacion', null=True),
        ),
        migrations.AddIndex(
            model_name='donaciones',
            index=models.Index(fields=['id_categoria'], name='Donaciones_idCateg_1c2823_idx'),
        ),
        
    ]
