# Generated by Django 4.2.29 on 2026-03-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_donaciones_referencia_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donaciones',
            name='id_tipo_donacion',
        ),
    ]
