# Generated by Django 4.2.29 on 2026-03-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_donaciones_id_tipo_donacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='imagen1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casos',
            name='imagen2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casos',
            name='imagen3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casos',
            name='imagen4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='ruta_imagen',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='evidencias',
            name='imagen1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='evidencias',
            name='imagen2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='evidencia1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='evidencia2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='evidencia3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
