# Generated by Django 4.2.29 on 2026-03-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_casos_imagen1_alter_casos_imagen2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencias',
            name='ruta_archivo',
        ),
        migrations.RemoveField(
            model_name='evidencias',
            name='tipo_archivo',
        ),
    ]
