# Generated by Django 4.2.29 on 2026-03-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_evidencias_ruta_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencias',
            name='imagen1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencias',
            name='imagen2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
